# drainmod7_soildata_ssurgo_builder.py
#
# First-pass DRAINMOD 7 soil builder from SSURGO/SDA.
#
# Purpose:
#   Build one soil file set per pixel using the stations CSV generated by the
#   DRAINMOD 7 weather script, following the structure of the native Larson files:
#       - .DMN  -> physical-chemical layer properties and links to MIS/WDV
#       - .MIS  -> multi-layer soil water characteristic file
#       - .SIN  -> representative soil water characteristic + Green-Ampt + upflux
#       - .WDV  -> water-table / volume-drained file
#
# Design choices:
#   1. Use the same layer boundaries and head grid as a working template MIS file.
#   2. Use SSURGO to derive water contents for each layer:
#         theta_s      from porosity ~= 1 - bulk_density / 2.65
#         theta_330    from wthirdbar_r / 100
#         theta_15000  from wfifteenbar_r / 100
#      and interpolate onto the template head grid.
#   3. Build the SIN SWCC from the top template layer using the same head grid as
#      the working SIN template.
#   4. Copy the Green-Ampt A/B table and the final SIN upflux table from the
#      working SIN template.
#   5. Build WDV by scaling each template layer's cumulative drained volume by the
#      ratio of drainable porosity:
#         (theta_s - theta_330)_SSURGO / (theta_s - theta_330)_template
#      This preserves the native file structure while allowing SSURGO to change
#      the amount of drainable water by layer.
#
# This is meant to be a conservative Illinois-ready starting point, not a final
# calibration workflow.
#
# Outputs:
#   - DMN/<pixel_id>.DMN
#   - MIS/<pixel_id>.MIS
#   - SIN/<pixel_id>.SIN
#   - WDV/<pixel_id>.WDV
#   - drainmod7_soil_map_<area>.csv
#   - drainmod7_soil_summary_<area>.csv
#   - mukey_samples_<area>.csv
#   - mukey_frequency_report_<area>.csv
#   - issues_<area>.csv

from __future__ import annotations

import csv
import os
import re
import time
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

SDA_URL = "https://sdmdataaccess.sc.egov.usda.gov/Tabular/post.rest"
RNG_SEED = 42
DEFAULT_N_SAMPLES_PER_PIXEL = 30

CONFIG_STATE_FILE = Path(__file__).with_name(Path(__file__).stem + "_last_config.json")


@dataclass
class RunConfig:
    stations_csv: Path
    base_dmn: Path
    base_sin: Path
    base_mis: Path
    base_wdv: Path
    output_dir: Path
    area_label: str
    limit_first_pixel: bool
    specific_pixel_id: str
    n_samples_per_pixel: int
    scale_template_wdv: bool


# ----------------------------
# Prompt helpers
# ----------------------------
def prompt_text(prompt: str, default: str | None = None, allow_blank: bool = False) -> str:
    suffix = f" [{default}]" if default not in {None, ""} else ""
    while True:
        value = input(f"{prompt}{suffix}: ").strip().strip('"').strip("'")
        if value:
            return value
        if default not in {None, ""}:
            return str(default)
        if allow_blank:
            return ""
        print("Please enter a value.")


def prompt_existing_file(prompt: str, default: Path | None = None) -> Path:
    while True:
        p = Path(prompt_text(prompt, str(default) if default else None)).expanduser()
        if p.exists() and p.is_file():
            return p
        print(f"File not found: {p}")


def prompt_output_dir(prompt: str, default: Path | None = None) -> Path:
    while True:
        p = Path(prompt_text(prompt, str(default) if default else None)).expanduser()
        try:
            p.mkdir(parents=True, exist_ok=True)
            return p
        except OSError as e:
            print(f"Could not create folder {p}: {e}")


def prompt_bool(message: str, default: bool) -> bool:
    shown = "y" if default else "n"
    raw = prompt_text(f"{message} (y/n)", shown).lower()
    return raw in {"y", "yes", "true", "1"}


def prompt_int(prompt: str, default: int, min_value: int = 0) -> int:
    while True:
        raw = prompt_text(prompt, str(default))
        try:
            value = int(raw)
            if value >= min_value:
                return value
        except ValueError:
            pass
        print(f"Please enter an integer >= {min_value}.")


def load_last_defaults() -> dict:
    if not CONFIG_STATE_FILE.exists():
        return {}
    try:
        return json.loads(CONFIG_STATE_FILE.read_text())
    except Exception:
        return {}


def save_last_defaults(cfg: RunConfig) -> None:
    payload = {
        "stations_csv": str(cfg.stations_csv),
        "base_dmn": str(cfg.base_dmn),
        "base_sin": str(cfg.base_sin),
        "base_mis": str(cfg.base_mis),
        "base_wdv": str(cfg.base_wdv),
        "output_dir": str(cfg.output_dir),
        "area_label": cfg.area_label,
        "limit_first_pixel": "y" if cfg.limit_first_pixel else "n",
        "specific_pixel_id": cfg.specific_pixel_id,
        "n_samples_per_pixel": cfg.n_samples_per_pixel,
        "scale_template_wdv": "y" if cfg.scale_template_wdv else "n",
    }
    try:
        CONFIG_STATE_FILE.write_text(json.dumps(payload, indent=2))
    except Exception:
        pass


# ----------------------------
# HTTP / SDA
# ----------------------------
def make_session() -> requests.Session:
    s = requests.Session()
    retry = Retry(
        total=6,
        connect=6,
        read=6,
        backoff_factor=0.8,
        status_forcelist=(429, 500, 502, 503, 504),
        allowed_methods=frozenset(["POST"]),
    )
    adapter = HTTPAdapter(max_retries=retry)
    s.mount("https://", adapter)
    s.mount("http://", adapter)
    return s


def run_sda(session: requests.Session, sql: str, expected_first_cols: list[str] | None = None) -> pd.DataFrame:
    r = session.post(SDA_URL, json={"format": "JSON", "query": sql}, timeout=300)
    r.raise_for_status()
    j = r.json()
    if "Error" in j and j["Error"]:
        raise RuntimeError(f"SDA Error: {j['Error']}")
    table = j.get("Table", None)
    if not table:
        return pd.DataFrame(columns=expected_first_cols or None)

    df = pd.DataFrame(table)
    if expected_first_cols and len(df.columns) >= len(expected_first_cols):
        numeric_like = all(str(c).isdigit() for c in df.columns[:len(expected_first_cols)])
        if numeric_like:
            rename_map = {df.columns[i]: expected_first_cols[i] for i in range(len(expected_first_cols))}
            df = df.rename(columns=rename_map)
    df.columns = [str(c).strip().lower() for c in df.columns]
    return df


# ----------------------------
# Stations and pixel handling
# ----------------------------
def load_stations_csv(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    cols = {c.strip().lower(): c for c in df.columns}
    required = ["pixel_id", "lat", "lon"]
    missing = [c for c in required if c not in cols]
    if missing:
        raise ValueError(f"Stations CSV is missing required columns: {missing}")
    out = df.rename(columns={cols["pixel_id"]: "pixel_id", cols["lat"]: "lat", cols["lon"]: "lon"}).copy()
    if "station6" in cols and cols["station6"] != "station6":
        out = out.rename(columns={cols["station6"]: "station6"})
    if "weather_id" in cols and cols["weather_id"] != "weather_id":
        out = out.rename(columns={cols["weather_id"]: "weather_id"})
    if "pixel_label" in cols and cols["pixel_label"] != "pixel_label":
        out = out.rename(columns={cols["pixel_label"]: "pixel_label"})
    out["pixel_id"] = out["pixel_id"].astype(str)
    out["lat"] = pd.to_numeric(out["lat"], errors="coerce")
    out["lon"] = pd.to_numeric(out["lon"], errors="coerce")
    out = out.dropna(subset=["lat", "lon"]).copy()
    out = out.sort_values("pixel_id").reset_index(drop=True)
    return out


def estimate_pixel_half_size(df_pts: pd.DataFrame) -> tuple[float, float]:
    lats = np.sort(df_pts["lat"].unique())
    lons = np.sort(df_pts["lon"].unique())
    dlat = float(np.min(np.diff(lats))) if len(lats) > 1 else 0.0
    dlon = float(np.min(np.diff(lons))) if len(lons) > 1 else 0.0
    half_dlat = dlat / 2.0
    half_dlon = dlon / 2.0
    if half_dlat == 0.0 and half_dlon > 0.0:
        half_dlat = half_dlon
    if half_dlon == 0.0 and half_dlat > 0.0:
        half_dlon = half_dlat
    if half_dlat == 0.0 and half_dlon == 0.0:
        half_dlat = 0.020833
        half_dlon = 0.020833
    return half_dlat, half_dlon


def sample_points_for_pixel(lat: float, lon: float, half_dlat: float, half_dlon: float, n: int, rng):
    dlat = rng.uniform(-half_dlat, half_dlat, size=n)
    dlon = rng.uniform(-half_dlon, half_dlon, size=n)
    return [(float(lat + a), float(lon + b)) for a, b in zip(dlat, dlon)]


# ----------------------------
# SDA SQL
# ----------------------------
def sql_mukey_votes_for_samples(samples_df: pd.DataFrame) -> str:
    parts = []
    for _, r in samples_df.iterrows():
        pid = str(r["pixel_id"])
        sid = int(r["sample_id"])
        lat = float(r["lat"])
        lon = float(r["lon"])
        wkt = f"point ({lon} {lat})"
        parts.append(f"SELECT '{pid}' AS pixel_id, {sid} AS sample_id, '{wkt}' AS wkt")
    union_sql = "\nUNION ALL\n".join(parts)
    return f"""
    WITH samp AS (
      {union_sql}
    )
    SELECT
      s.pixel_id,
      s.sample_id,
      CAST(mu.mukey AS BIGINT) AS mukey
    FROM samp s
    CROSS APPLY SDA_Get_Mukey_from_intersection_with_WktWgs84(s.wkt) mu;
    """


def sql_component_horizons_for_mukeys(mukeys: list[int]) -> str:
    mukey_list = ",".join(str(int(m)) for m in mukeys)
    return f"""
    SELECT
      mu.mukey,
      mu.muname,
      comp.cokey,
      comp.compname,
      comp.comppct_r,
      comp.hydgrp,
      comp.drainagecl,
      hz.hzname,
      hz.desgnmaster,
      hz.hzdept_r,
      hz.hzdepb_r,
      hz.wthirdbar_r,
      hz.wfifteenbar_r,
      hz.sandtotal_r,
      hz.silttotal_r,
      hz.claytotal_r,
      hz.dbthirdbar_r,
      hz.ksat_r,
      hz.om_r,
      hz.ph1to1h2o_r
    FROM mapunit mu
    INNER JOIN component comp ON comp.mukey = mu.mukey
    INNER JOIN chorizon hz ON hz.cokey = comp.cokey
    WHERE mu.mukey IN ({mukey_list})
      AND comp.majcompflag = 'Yes'
      AND hz.hzdept_r IS NOT NULL
      AND hz.hzdepb_r IS NOT NULL
    ORDER BY mu.mukey, comp.comppct_r DESC, hz.hzdept_r ASC;
    """


# ----------------------------
# Template parsers
# ----------------------------
def parse_mis_template(path: Path) -> dict:
    lines = path.read_text(errors="ignore").splitlines()
    n_layers = int(lines[0].strip())
    i = 1
    layers = []
    while i < len(lines):
        while i < len(lines) and not lines[i].strip().startswith("*TOP"):
            i += 1
        if i >= len(lines):
            break
        top_bot = lines[i + 1].split()
        top = float(top_bot[0]); bottom = float(top_bot[1])
        npts = int(lines[i + 3].strip())
        pts = []
        for j in range(npts):
            vals = lines[i + 4 + j].split()
            pts.append((float(vals[0]), float(vals[1])))
        layers.append({"top": top, "bottom": bottom, "points": pts})
        i = i + 4 + npts
    if len(layers) != n_layers:
        raise ValueError(f"Template MIS says {n_layers} layers but parsed {len(layers)}.")
    heads = [float(h) for _, h in layers[0]["points"]]
    return {"n_layers": n_layers, "layers": layers, "heads": heads}


def parse_sin_template(path: Path) -> dict:
    lines = path.read_text(errors="ignore").splitlines()
    title = lines[0]
    count_line = lines[1].strip()
    if len(count_line) < 4 or not count_line[:4].isdigit():
        raise ValueError(f"Could not parse SIN count line: {count_line}")
    n_swcc = int(count_line[:2])
    n_ab = int(count_line[2:4])

    swcc = []
    i = 2
    for _ in range(n_swcc):
        vals = lines[i].split()
        swcc.append((float(vals[0]), float(vals[1])))
        i += 1

    ab_rows = []
    for _ in range(n_ab):
        vals = lines[i].split()
        ab_rows.append((float(vals[0]), float(vals[1]), float(vals[2])))
        i += 1

    n_wtd = int(lines[i].strip())
    i += 1
    wtd_rows = []
    for _ in range(n_wtd):
        vals = lines[i].split()
        wtd_rows.append((float(vals[0]), float(vals[1]), float(vals[2])))
        i += 1

    return {
        "title": title,
        "swcc": swcc,
        "swcc_heads": [abs(h) for _, h in swcc],
        "ab_rows": ab_rows,
        "wtd_rows": wtd_rows,
    }


def parse_wdv_template(path: Path) -> list[dict]:
    lines = path.read_text(errors="ignore").splitlines()
    sections = []
    i = 0
    while i < len(lines):
        if lines[i].strip().startswith("*TLAYER"):
            hdr = lines[i + 1].split()
            top = float(hdr[0]); bottom = float(hdr[1]); npts = int(hdr[2])
            if not lines[i + 2].strip().startswith("*WATER TABLE"):
                raise ValueError("WDV template missing *WATER TABLE VOLUME DRAINED after layer header.")
            rows = []
            for j in range(npts):
                vals = lines[i + 3 + j].split()
                rows.append((float(vals[0]), float(vals[1])))
            sections.append({"top": top, "bottom": bottom, "rows": rows})
            i = i + 3 + npts
        else:
            i += 1
    return sections


def parse_dmn_template(path: Path) -> dict:
    lines = path.read_text(errors="ignore").splitlines()

    idx_field = next((i for i, ln in enumerate(lines) if ln.strip().startswith("*Field")), -1)
    idx_crops = next((i for i, ln in enumerate(lines) if ln.strip().startswith("*Crops")), -1)
    if idx_field == -1 or idx_crops == -1 or idx_crops <= idx_field:
        raise ValueError("Could not locate *Field and *Crops sections in the DMN template.")

    idx_soil_files = next((i for i in range(idx_field, idx_crops) if lines[i].strip().startswith("&Soil files")), -1)
    idx_prof = next((i for i in range(idx_field, idx_crops) if lines[i].strip().startswith("&ProfDepth")), -1)
    idx_layer_header = next((i for i in range(idx_field, idx_crops) if lines[i].strip().startswith("&L")), -1)
    if min(idx_soil_files, idx_prof, idx_layer_header) == -1:
        raise ValueError("DMN template is missing &Soil files, &ProfDepth, or &L field table markers.")

    prof_vals = lines[idx_prof + 1].split()
    if len(prof_vals) < 3:
        raise ValueError("Could not parse the DMN &ProfDepth line.")
    prof_depth = float(prof_vals[0])
    yes_wtd = float(prof_vals[1])
    yes_ddz = float(prof_vals[2])

    layer_rows = []
    i = idx_layer_header + 1
    while i < idx_crops:
        s = lines[i].strip()
        if not s:
            i += 1
            continue
        if s.startswith("*") or s.startswith("&"):
            break
        vals = lines[i].split()
        if len(vals) >= 10 and vals[0].isdigit():
            layer_rows.append({
                "layer": int(vals[0]),
                "depsoil": float(vals[1]),
                "hydrcond": float(vals[2]),
                "wltpnt": float(vals[3]),
                "clyfrc": float(vals[4]),
                "sltfrc": float(vals[5]),
                "rho_b": float(vals[6]),
                "soilph": float(vals[7]),
                "k_d": float(vals[8]),
                "fc": float(vals[9]),
            })
        i += 1

    return {
        "pre_lines": lines[:idx_field],
        "post_lines": lines[idx_crops:],
        "prof_depth": prof_depth,
        "yes_wtd": yes_wtd,
        "yes_ddz": yes_ddz,
        "layer_rows": layer_rows,
    }


def _fmt_dmn_layer_row(layer_no: int, depsoil: float, hydrcond: float, wltpnt: float,
                       clyfrc: float, sltfrc: float, rho_b: float, soilph: float,
                       k_d: float, fc: float) -> str:
    return (
        f"{layer_no:2d}"
        f"{depsoil:9.1f}"
        f"{hydrcond:9.2f}"
        f"{wltpnt:9.3f}"
        f"{clyfrc:9.3f}"
        f"{sltfrc:9.3f}"
        f"{rho_b:9.2f}"
        f"{soilph:9.1f}"
        f"{k_d:9.2f}"
        f"{fc:6.2f}"
    )


def write_dmn(path: Path, template: dict, mis_path: Path, wdv_path: Path, layer_rows: list[dict]) -> None:
    lines = []
    lines.extend(template["pre_lines"])
    lines.append("*Field")
    lines.append("&=====")
    lines.append("&Soil files")
    lines.append(str(mis_path.resolve()))
    lines.append(str(wdv_path.resolve()))
    lines.append("&ProfDepth    YesWTD    YesDDZ")
    prof_depth = float(layer_rows[-1]["depsoil"]) if layer_rows else float(template["prof_depth"])
    lines.append(f"{prof_depth:10.1f}{float(template['yes_wtd']):10.1f}{float(template['yes_ddz']):10.1f}")
    lines.append("&L  DEPsoil HydrCond   WltPnt   ClyFrc   SltFrc    Rho_b   SoilpH      K_d    FC")
    for row in layer_rows:
        lines.append(
            _fmt_dmn_layer_row(
                int(row["layer"]), float(row["depsoil"]), float(row["hydrcond"]),
                float(row["wltpnt"]), float(row["clyfrc"]), float(row["sltfrc"]),
                float(row["rho_b"]), float(row["soilph"]), float(row["k_d"]), float(row["fc"])
            )
        )
    lines.extend(template["post_lines"])
    text = "\r\n".join(lines) + "\r\n"
    path.write_bytes(text.encode("ascii", "ignore"))


# ----------------------------
# Retention functions
# ----------------------------
def clamp01(x: float) -> float:
    return max(0.0, min(1.0, float(x)))


def theta_from_piecewise(head_cm: float, theta_s: float, theta_330: float, theta_15000: float) -> float:
    h = float(head_cm)
    theta_s = clamp01(theta_s)
    theta_330 = clamp01(min(theta_330, theta_s - 1e-4))
    theta_15000 = clamp01(min(theta_15000, theta_330 - 1e-4))

    if h <= 0:
        return theta_s
    if h <= 330:
        x = np.log10(max(h, 1.0)) / np.log10(330.0)
        return float(theta_s + (theta_330 - theta_s) * x)
    if h <= 15000:
        x = (np.log10(h) - np.log10(330.0)) / (np.log10(15000.0) - np.log10(330.0))
        return float(theta_330 + (theta_15000 - theta_330) * x)
    return theta_15000


def build_retention_points(theta_s: float, theta_330: float, theta_15000: float, heads_cm: list[float]) -> list[tuple[float, float]]:
    return [(theta_from_piecewise(h, theta_s, theta_330, theta_15000), float(h)) for h in heads_cm]


def calc_theta_s_from_bd(dbthirdbar_r: float | None) -> float:
    if pd.isna(dbthirdbar_r):
        return np.nan
    theta_s = 1.0 - float(dbthirdbar_r) / 2.65
    return float(max(0.25, min(0.75, theta_s)))


def aggregate_props_for_interval(hz: pd.DataFrame, z0: float, z1: float) -> dict | None:
    rows = []
    for _, r in hz.iterrows():
        top = float(r["hzdept_r"])
        bot = float(r["hzdepb_r"])
        overlap = max(0.0, min(bot, z1) - max(top, z0))
        if overlap <= 0:
            continue
        rows.append((overlap, r))
    if not rows:
        return None

    def wavg(col):
        vals = [(w, float(rr[col])) for w, rr in rows if pd.notna(rr.get(col))]
        if not vals:
            return np.nan
        return sum(w * v for w, v in vals) / sum(w for w, _ in vals)

    theta_330 = wavg("wthirdbar_r")
    theta_15000 = wavg("wfifteenbar_r")
    db = wavg("dbthirdbar_r")
    ksat = wavg("ksat_r")
    clay = wavg("claytotal_r")
    silt = wavg("silttotal_r")
    sand = wavg("sandtotal_r")
    om = wavg("om_r")
    ph = wavg("ph1to1h2o_r")

    theta_330 = theta_330 / 100.0 if pd.notna(theta_330) else np.nan
    theta_15000 = theta_15000 / 100.0 if pd.notna(theta_15000) else np.nan
    theta_s = calc_theta_s_from_bd(db)

    if pd.notna(theta_s) and pd.notna(theta_330) and theta_330 >= theta_s:
        theta_330 = max(0.01, theta_s - 0.01)
    if pd.notna(theta_330) and pd.notna(theta_15000) and theta_15000 >= theta_330:
        theta_15000 = max(0.01, theta_330 - 0.01)

    return {
        "theta_s": theta_s,
        "theta_330": theta_330,
        "theta_15000": theta_15000,
        "db": db,
        "ksat_um_s": ksat,
        "clay": clay,
        "silt": silt,
        "sand": sand,
        "om": om,
        "ph": ph,
    }


# ----------------------------
# File writers
# ----------------------------
def write_mis(path: Path, layers: list[dict]) -> None:
    lines = [f"{len(layers):4d}"]
    for lyr in layers:
        lines.append(" *TOP AND BOTTOM OF LAYER")
        lines.append(f"{float(lyr['top']):8.1f}{float(lyr['bottom']):8.1f}")
        lines.append(" *NUMBER OF POINTS IN LAYER")
        lines.append(f"{len(lyr['points']):4d}")
        for theta, head in lyr["points"]:
            lines.append(f"{float(theta):7.5f}{float(head):12.1f}")
    text = "\r\n".join(lines) + "\r\n"
    path.write_bytes(text.encode("ascii", "ignore"))


def write_sin(path: Path, title: str, swcc_points: list[tuple[float, float]], ab_rows: list[tuple[float, float, float]], wtd_rows: list[tuple[float, float, float]]) -> None:
    n_swcc = len(swcc_points)
    n_ab = len(ab_rows)
    n_wtd = len(wtd_rows)
    lines = [title[:72], f"{n_swcc:02d}{n_ab:02d}"]

    for theta, head in swcc_points:
        head_out = 0.0 if abs(float(head)) < 1e-12 else -abs(float(head))
        lines.append(f"{float(theta):10.5f}{float(head_out):11.1f}")

    for d, a, b in ab_rows:
        lines.append(f"{float(d):10.4f}{float(a):10.4f}{float(b):10.4f}")

    lines.append(f"{n_wtd:d}")
    for d, vol, flux in wtd_rows:
        lines.append(f"{float(d):10.2f}{float(vol):10.2f}{float(flux):10.2f}")

    text = "\r\n".join(lines) + "\r\n"
    path.write_bytes(text.encode("ascii", "ignore"))


def write_wdv(path: Path, sections: list[dict]) -> None:
    lines = ["*NLAYER", f"{len(sections):3d}"]
    for sec in sections:
        rows = sec["rows"]
        lines.append("*TLAYER BLAYER NPTS")
        lines.append(f"{float(sec['top']):7.1f}{float(sec['bottom']):8.1f}{len(rows):5d}")
        lines.append("*WATER TABLE  VOLUME DRAINED")
        for wt, vd in rows:
            lines.append(f"{float(wt):8.0f}{float(vd):14.5f}")
    text = "\r\n".join(lines) + "\r\n"
    path.write_bytes(text.encode("ascii", "ignore"))


# ----------------------------
# Main builder
# ----------------------------
def build_interactive_config() -> RunConfig:
    print("DRAINMOD 7 SSURGO soil builder")
    print("This version builds DMN, MIS, SIN, and WDV using SSURGO plus native template structure.")
    print("It follows the layer structure of the template MIS/WDV and the SIN table structure of the template SIN.")
    print("It also patches the DMN field layer table so the physical-chemical properties stay consistent with the soil files.")
    last = load_last_defaults()

    stations_csv = prompt_existing_file("Stations CSV file", Path(last["stations_csv"]) if last.get("stations_csv") else None)
    base_dmn = prompt_existing_file("Base DMN template file", Path(last["base_dmn"]) if last.get("base_dmn") else None)
    base_sin = prompt_existing_file("Base SIN template file", Path(last["base_sin"]) if last.get("base_sin") else None)
    base_mis = prompt_existing_file("Base MIS template file", Path(last["base_mis"]) if last.get("base_mis") else None)
    base_wdv = prompt_existing_file("Base WDV template file", Path(last["base_wdv"]) if last.get("base_wdv") else None)

    output_default = Path(last["output_dir"]) if last.get("output_dir") else stations_csv.parent.parent / "SOIL" / stations_csv.parent.name
    output_dir = prompt_output_dir("Folder where the DRAINMOD 7 soil files should be saved", output_default)

    area_default = last.get("area_label", output_dir.name)
    area_label = prompt_text("Area label for output files", area_default)

    limit_first_pixel = prompt_bool(
        "Limit to only the first pixel",
        str(last.get("limit_first_pixel", "n")).lower().startswith("y"),
    )
    specific_pixel_id = prompt_text(
        "Specific pixel_id to run (leave blank for all remaining pixels)",
        str(last.get("specific_pixel_id", "")),
        allow_blank=True,
    )
    n_samples_per_pixel = prompt_int(
        "Number of random SSURGO samples per pixel",
        int(last.get("n_samples_per_pixel", DEFAULT_N_SAMPLES_PER_PIXEL)),
        1,
    )
    scale_template_wdv = prompt_bool(
        "Scale the template WDV by SSURGO drainable porosity ratios",
        str(last.get("scale_template_wdv", "y")).lower().startswith("y"),
    )

    cfg = RunConfig(
        stations_csv=stations_csv,
        base_dmn=base_dmn,
        base_sin=base_sin,
        base_mis=base_mis,
        base_wdv=base_wdv,
        output_dir=output_dir,
        area_label=area_label,
        limit_first_pixel=limit_first_pixel,
        specific_pixel_id=specific_pixel_id.strip(),
        n_samples_per_pixel=n_samples_per_pixel,
        scale_template_wdv=scale_template_wdv,
    )
    save_last_defaults(cfg)
    return cfg


def choose_representative_mukey(votes: pd.DataFrame) -> dict:
    rep = {}
    for pid, g in votes.groupby("pixel_id"):
        counts = g["mukey"].value_counts()
        if counts.empty:
            continue
        maxc = counts.max()
        tied = sorted([int(m) for m, c in counts.items() if c == maxc])
        rep[str(pid)] = int(tied[0])
    return rep


def build_mukey_frequency_report(samples_with_votes: pd.DataFrame) -> pd.DataFrame:
    freq_rows = []
    total_samples_by_pixel = samples_with_votes.groupby("pixel_id")["sample_id"].count()
    votes_nonnull = samples_with_votes.dropna(subset=["mukey"]).copy()
    valid_hits_by_pixel = votes_nonnull.groupby("pixel_id")["mukey"].count()
    for pid, g in samples_with_votes.groupby("pixel_id"):
        total_samples = int(total_samples_by_pixel.get(pid, 0))
        valid_hits = int(valid_hits_by_pixel.get(pid, 0))
        g_valid = g.dropna(subset=["mukey"]).copy()
        if g_valid.empty:
            freq_rows.append({
                "pixel_id": str(pid),
                "total_samples": total_samples,
                "valid_mukey_hits": valid_hits,
                "n_unique_mukeys": 0,
                "representative_mukey": np.nan,
                "representative_count": 0,
                "representative_fraction_of_valid": np.nan,
                "all_mukeys_found": "",
            })
            continue
        counts = g_valid["mukey"].astype("Int64").astype(int).value_counts().sort_values(ascending=False)
        maxc = counts.max()
        tied = sorted([int(m) for m, c in counts.items() if c == maxc])
        rep_mukey = tied[0]
        rep_count = int(counts.loc[rep_mukey])
        rep_frac = rep_count / valid_hits if valid_hits > 0 else np.nan
        parts = [f"{int(mk)}:{int(ct)} ({ct/valid_hits:.3f})" for mk, ct in counts.items()]
        freq_rows.append({
            "pixel_id": str(pid),
            "total_samples": total_samples,
            "valid_mukey_hits": valid_hits,
            "n_unique_mukeys": int(counts.shape[0]),
            "representative_mukey": int(rep_mukey),
            "representative_count": rep_count,
            "representative_fraction_of_valid": rep_frac,
            "all_mukeys_found": "; ".join(parts),
        })
    return pd.DataFrame(freq_rows).sort_values("pixel_id").reset_index(drop=True)


def main():
    t0 = time.time()
    cfg = build_interactive_config()

    out_dmn = cfg.output_dir / "DMN"
    out_mis = cfg.output_dir / "MIS"
    out_sin = cfg.output_dir / "SIN"
    out_wdv = cfg.output_dir / "WDV"
    out_dmn.mkdir(parents=True, exist_ok=True)
    out_mis.mkdir(parents=True, exist_ok=True)
    out_sin.mkdir(parents=True, exist_ok=True)
    out_wdv.mkdir(parents=True, exist_ok=True)

    df_pts = load_stations_csv(cfg.stations_csv)
    if cfg.limit_first_pixel:
        df_pts = df_pts.iloc[[0]].copy().reset_index(drop=True)
    if cfg.specific_pixel_id:
        df_pts = df_pts[df_pts["pixel_id"].astype(str) == cfg.specific_pixel_id].copy().reset_index(drop=True)
    if df_pts.empty:
        raise RuntimeError("No pixels remain after applying the selected filters.")

    dmn_template = parse_dmn_template(cfg.base_dmn)
    mis_template = parse_mis_template(cfg.base_mis)
    sin_template = parse_sin_template(cfg.base_sin)
    wdv_template = parse_wdv_template(cfg.base_wdv)

    if len(mis_template["layers"]) != len(wdv_template):
        raise RuntimeError(
            f"Template MIS has {len(mis_template['layers'])} layers but template WDV has {len(wdv_template)}. "
            "Use matching native templates."
        )

    rng = np.random.default_rng(RNG_SEED)
    half_dlat, half_dlon = estimate_pixel_half_size(df_pts)

    # Build sampled points
    sample_rows = []
    for _, row in df_pts.iterrows():
        pts = sample_points_for_pixel(float(row["lat"]), float(row["lon"]), half_dlat, half_dlon, cfg.n_samples_per_pixel, rng)
        for sid, (lat, lon) in enumerate(pts, start=1):
            sample_rows.append({"pixel_id": str(row["pixel_id"]), "sample_id": sid, "lat": lat, "lon": lon})
    samples_df = pd.DataFrame(sample_rows)

    print(f"Pixels to build: {len(df_pts)}")
    print(f"Random samples per pixel: {cfg.n_samples_per_pixel}")
    print(f"Template MIS layers: {len(mis_template['layers'])}")
    print(f"Template DMN layers: {len(dmn_template['layer_rows'])}")

    session = make_session()

    # Mukey vote query in chunks
    vote_frames = []
    chunk_size = 150
    i = 0
    while i < len(samples_df):
        samp_chunk = samples_df.iloc[i:i + chunk_size].copy()
        sql_votes = sql_mukey_votes_for_samples(samp_chunk)
        v = run_sda(session, sql_votes, expected_first_cols=["pixel_id", "sample_id", "mukey"])
        if not v.empty:
            vote_frames.append(v)
        print(f"  vote chunk: idx {i}-{i + len(samp_chunk) - 1} -> {0 if v.empty else len(v)} rows")
        i += len(samp_chunk)

    votes = pd.concat(vote_frames, ignore_index=True) if vote_frames else pd.DataFrame()
    if votes.empty:
        raise RuntimeError("SDA returned no mukey results for sampled points.")

    votes["pixel_id"] = votes["pixel_id"].astype(str)
    votes["sample_id"] = pd.to_numeric(votes["sample_id"], errors="coerce").astype("Int64")
    votes["mukey"] = pd.to_numeric(votes["mukey"], errors="coerce").astype("Int64")

    samples_with_votes = samples_df.merge(votes, on=["pixel_id", "sample_id"], how="left")
    rep_map = choose_representative_mukey(votes.dropna(subset=["mukey"]))
    df_pts["mukey_rep"] = df_pts["pixel_id"].map(rep_map)

    freq_df = build_mukey_frequency_report(samples_with_votes)
    freq_lookup = freq_df.set_index("pixel_id")
    df_pts["mukey_valid_hits"] = df_pts["pixel_id"].map(freq_lookup["valid_mukey_hits"]) if not freq_df.empty else np.nan

    used_mukeys = sorted({int(m) for m in df_pts["mukey_rep"].dropna().tolist()})
    if not used_mukeys:
        raise RuntimeError("No representative mukeys were assigned to pixels.")

    hz_all = run_sda(
        session,
        sql_component_horizons_for_mukeys(used_mukeys),
        expected_first_cols=[
            "mukey", "muname", "cokey", "compname", "comppct_r", "hydgrp", "drainagecl",
            "hzname", "desgnmaster", "hzdept_r", "hzdepb_r", "wthirdbar_r", "wfifteenbar_r",
            "sandtotal_r", "silttotal_r", "claytotal_r", "dbthirdbar_r", "ksat_r",
            "om_r", "ph1to1h2o_r"
        ],
    )

    numeric_cols = [
        "mukey", "cokey", "comppct_r", "hzdept_r", "hzdepb_r",
        "wthirdbar_r", "wfifteenbar_r", "sandtotal_r", "silttotal_r",
        "claytotal_r", "dbthirdbar_r", "ksat_r", "om_r", "ph1to1h2o_r"
    ]
    for c in numeric_cols:
        if c in hz_all.columns:
            hz_all[c] = pd.to_numeric(hz_all[c], errors="coerce")

    issues = []
    summary_rows = []
    soil_map_rows = []

    # Precompute template drainable porosity by layer using template MIS
    template_dp_by_layer = {}
    for sec, mis_lyr in zip(wdv_template, mis_template["layers"]):
        points = mis_lyr["points"]
        theta0 = float(points[0][0])
        theta330 = None
        for th, hd in points:
            if abs(float(hd) - 330.0) < 1e-6:
                theta330 = float(th)
                break
        if theta330 is None:
            theta330 = float(points[min(len(points)-1, 7)][0])
        template_dp_by_layer[(sec["top"], sec["bottom"])] = max(1e-6, theta0 - theta330)

    for _, p in df_pts.iterrows():
        pixel_id = str(p["pixel_id"])
        mukey = p["mukey_rep"]
        if pd.isna(mukey):
            issues.append({"pixel_id": pixel_id, "issue": "No representative mukey found."})
            continue

        hz_m = hz_all[hz_all["mukey"] == int(mukey)].copy()
        if hz_m.empty:
            issues.append({"pixel_id": pixel_id, "issue": f"No SSURGO horizons returned for mukey {int(mukey)}."})
            continue

        # dominant component only
        comp_order = (
            hz_m[["cokey", "compname", "comppct_r", "muname", "hydgrp", "drainagecl"]]
            .drop_duplicates()
            .sort_values(["comppct_r", "cokey"], ascending=[False, True])
            .reset_index(drop=True)
        )
        dom = comp_order.iloc[0]
        cokey = int(dom["cokey"])
        hz = hz_m[hz_m["cokey"] == cokey].copy().sort_values(["hzdept_r", "hzdepb_r"]).reset_index(drop=True)
        if hz.empty:
            issues.append({"pixel_id": pixel_id, "issue": f"No horizons for dominant component in mukey {int(mukey)}."})
            continue

        # Build MIS layers using template layer boundaries
        mis_layers = []
        ssurgo_dp_by_layer = {}
        for tlyr in mis_template["layers"]:
            z0 = float(tlyr["top"])
            z1 = float(tlyr["bottom"])
            props = aggregate_props_for_interval(hz, z0, z1)
            if props is None:
                continue
            pts = build_retention_points(props["theta_s"], props["theta_330"], props["theta_15000"], mis_template["heads"])
            mis_layers.append({"top": z0, "bottom": z1, "points": pts, **props})
            ssurgo_dp_by_layer[(z0, z1)] = max(1e-6, float(props["theta_s"] - props["theta_330"]))

        if not mis_layers:
            issues.append({"pixel_id": pixel_id, "issue": "No MIS layers could be built from SSURGO."})
            continue

        # SIN from top template layer
        top_props = mis_layers[0]
        sin_heads = sin_template["swcc_heads"]
        sin_swcc = build_retention_points(top_props["theta_s"], top_props["theta_330"], top_props["theta_15000"], sin_heads)

        sin_title = f"{len(mis_layers)} layer sample soil - {pixel_id}, {str(dom['compname']).strip()}"
        sin_ab = sin_template["ab_rows"]
        sin_wtd = sin_template["wtd_rows"]

        # WDV based on template structure; optionally scale by drainable porosity ratio
        wdv_sections = []
        for sec in wdv_template:
            z0 = float(sec["top"]); z1 = float(sec["bottom"])
            base_rows = sec["rows"]
            if cfg.scale_template_wdv:
                dp_t = template_dp_by_layer.get((z0, z1), 1.0)
                dp_s = ssurgo_dp_by_layer.get((z0, z1), dp_t)
                ratio = dp_s / dp_t if dp_t > 0 else 1.0
            else:
                ratio = 1.0
            scaled_rows = [(wt, vd * ratio) for wt, vd in base_rows]
            wdv_sections.append({"top": z0, "bottom": z1, "rows": scaled_rows})

        # DMN layer table from the same SSURGO-aggregated layer intervals
        dmn_template_rows = dmn_template["layer_rows"]
        default_kd = float(dmn_template_rows[0]["k_d"]) if dmn_template_rows else 2.60
        dmn_rows = []
        for idx, lyr in enumerate(mis_layers, start=1):
            kd_val = float(dmn_template_rows[idx - 1]["k_d"]) if idx - 1 < len(dmn_template_rows) else default_kd
            ksat_cm_hr = float(lyr["ksat_um_s"]) * 0.36 if pd.notna(lyr["ksat_um_s"]) else (
                float(dmn_template_rows[idx - 1]["hydrcond"]) if idx - 1 < len(dmn_template_rows) else 1.0
            )
            dmn_rows.append({
                "layer": idx,
                "depsoil": float(lyr["bottom"]),
                "hydrcond": max(0.01, ksat_cm_hr),
                "wltpnt": max(0.01, float(lyr["theta_15000"])),
                "clyfrc": max(0.0, min(1.0, float(lyr["clay"]) / 100.0 if pd.notna(lyr["clay"]) else 0.25)),
                "sltfrc": max(0.0, min(1.0, float(lyr["silt"]) / 100.0 if pd.notna(lyr["silt"]) else 0.35)),
                "rho_b": float(lyr["db"]) if pd.notna(lyr["db"]) else (
                    float(dmn_template_rows[idx - 1]["rho_b"]) if idx - 1 < len(dmn_template_rows) else 1.5
                ),
                "soilph": float(lyr["ph"]) if pd.notna(lyr["ph"]) else (
                    float(dmn_template_rows[idx - 1]["soilph"]) if idx - 1 < len(dmn_template_rows) else 6.5
                ),
                "k_d": kd_val,
                "fc": max(0.01, float(lyr["theta_330"])),
            })

        dmn_path = out_dmn / f"{pixel_id}.DMN"
        mis_path = out_mis / f"{pixel_id}.MIS"
        sin_path = out_sin / f"{pixel_id}.SIN"
        wdv_path = out_wdv / f"{pixel_id}.WDV"

        write_dmn(dmn_path, dmn_template, mis_path, wdv_path, dmn_rows)
        write_mis(mis_path, mis_layers)
        write_sin(sin_path, sin_title, sin_swcc, sin_ab, sin_wtd)
        write_wdv(wdv_path, wdv_sections)

        soil_map_rows.append({
            "pixel_id": pixel_id,
            "pixel_label": p.get("pixel_label", ""),
            "station6": p.get("station6", ""),
            "weather_id": p.get("weather_id", ""),
            "mukey_rep": int(mukey),
            "dominant_cokey": cokey,
            "muname": str(dom["muname"]).strip(),
            "compname": str(dom["compname"]).strip(),
            "dmn_file": str(dmn_path),
            "mis_file": str(mis_path),
            "sin_file": str(sin_path),
            "wdv_file": str(wdv_path),
        })

        summary_rows.append({
            "pixel_id": pixel_id,
            "mukey_rep": int(mukey),
            "dominant_cokey": cokey,
            "muname": str(dom["muname"]).strip(),
            "compname": str(dom["compname"]).strip(),
            "hydgrp": str(dom["hydgrp"]).strip(),
            "drainagecl": str(dom["drainagecl"]).strip(),
            "n_mis_layers": len(mis_layers),
            "top_theta_s": round(float(top_props["theta_s"]), 4),
            "top_theta_330": round(float(top_props["theta_330"]), 4),
            "top_theta_15000": round(float(top_props["theta_15000"]), 4),
            "top_db": round(float(top_props["db"]), 4) if pd.notna(top_props["db"]) else np.nan,
            "top_ksat_um_s": round(float(top_props["ksat_um_s"]), 2) if pd.notna(top_props["ksat_um_s"]) else np.nan,
            "top_ksat_cm_hr": round(float(dmn_rows[0]["hydrcond"]), 3) if dmn_rows else np.nan,
            "top_soilph": round(float(dmn_rows[0]["soilph"]), 2) if dmn_rows else np.nan,
            "top_kd": round(float(dmn_rows[0]["k_d"]), 2) if dmn_rows else np.nan,
        })

        print(f"Built soil files for {pixel_id}: mukey={int(mukey)} component={str(dom['compname']).strip()}")

    # Save outputs
    area_tag = re.sub(r"[^A-Za-z0-9_]+", "_", cfg.area_label).strip("_") or "area"
    samples_with_votes.to_csv(cfg.output_dir / f"mukey_samples_{area_tag}.csv", index=False)
    freq_df.to_csv(cfg.output_dir / f"mukey_frequency_report_{area_tag}.csv", index=False)
    pd.DataFrame(soil_map_rows).to_csv(cfg.output_dir / f"drainmod7_soil_map_{area_tag}.csv", index=False)
    pd.DataFrame(summary_rows).to_csv(cfg.output_dir / f"drainmod7_soil_summary_{area_tag}.csv", index=False)
    if issues:
        pd.DataFrame(issues).to_csv(cfg.output_dir / f"issues_{area_tag}.csv", index=False)

    print(f"\nElapsed: {(time.time() - t0)/60:.1f} minutes")
    print(f"Files written under: {cfg.output_dir}")
    print("Important:")
    print("  - DMN was patched from the native template and updated with SSURGO-derived layer properties.")
    print("  - MIS was built from SSURGO onto the native template layer structure.")
    print("  - SIN SWCC was built from the top MIS layer; A/B and upflux tables came from the template SIN.")
    print("  - WDV kept the native template structure and was optionally scaled by SSURGO drainable porosity ratios.")
    print("This is a strong first-pass builder for DRAINMOD 7, but DMN K_d, WDV, and SIN A/B are still the first parts to revisit during calibration.")


if __name__ == "__main__":
    main()
